### PR TITLE
157737345 Ft admin homepage

### PR DESCRIPTION
**Pull request by Melvin1Atieno**
**What does this PR do?**
1.Adds an admin homepage design
**Description of Task to be completed?**
1.Adds a design for admin dashboard
2. Adds design for admin requests table.
3. adds logout option for logged in admin
**How this should be manually tested**
1.Git clone repo, checkout ft-admin-homepage-dashboard-157737345
**Relevant pivotal tracker stories**
[#157737345] (https://www.pivotaltracker.com/story/show/157737345)
link :
**Screenshots**
dashboard
requests

### CODE REVIEW

**Comment by dessHub** [comment]
UI is awesome , Github best practices are adhered to. I like the fact that you have kept improving on your deploymnents

**Comment by asamisellah** [comment]
To make your titles bold use, put a space btwn '#' and the next word. i.e. `# word`

**Comment by gtsofa** [comment]
Nice PR, your designs look great

**Comment by PaulKitonyi** [comment]
Nice PR and UI.If you need to make your PT id clickable use, [#PTid](then your url here)

**Pull request merged**
