### PR TITLE
157736626 ft user login page

### PR DESCRIPTION
**Pull request by Melvin1Atieno**
**What does this PR do?**:
Creates a Login page for MnR Tracker web app.

**Description of task to be completed**
Create a user login/ landing page.

**How this can be manually tested**
  Clone the repo, checkout 157736626-ft-User-login-page.

 
*relevant pivotal tracker story*:
https://www.pivotaltracker.com/story/show/157736626

*Feedback required*
 A quick pair of eyes on the code.
 critique on the design

*Quick view of the page
capturep
*

### CODE REVIEW

**Comment by lawrenceChege** [comment]
hey, your UI is great. and your commits are short and precise.
kindly check out this doc (https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by gtsofa** [comment]
Nice UI!!. Kindly checkout the document for git naming conventions and best practices and fix your  branch name.

**Comment by asamisellah** [comment]
Hey, here's a link to help you with the PR structure https://github.com/asamisellah/Maintenance-Tracker/pull/1

**Comment by PaulKitonyi** [comment]
Hey @Melvin1Atieno congrats for having your first commit.I made mine yesterday and got feedback from our fellow bootcampers and now i'm glad they are saying that i'm improving.You have a great UI.Please consider that link shared by @lawrenceChege it has really helped me.Also consider aligning your submit button at the centre of the form.

**Comment by Melvin1Atieno** [comment]
@lawrenceChege @gtsofa @asamisellah On it. thank you.
@PaulKitonyi  thank you I will.

**Comment by PaulKitonyi** [comment]
Yeah i think good alignment contributes highly to user experince when
he/she uses your appliacation.It feels good to use an organised app.

**Pull request merged**
