### PR TITLE
# Ft 157737526 user homepage 

### PR DESCRIPTION
**Pull request by Melvin1Atieno**
#### What does this PR do?
Adds a user homepage design.
#### Description of the Task completed 
Adds a page where a 
user can create a request.
Adds a page where a user can see their requests, edit and delete them.
#### How should this be manually tested.
clone repository checkout ft-user-homepage-157737526
#### pivotal tracker stories.
157737526
#### screenshots
captureuc
captureur

### CODE REVIEW

**Comment by alovega** [comment]
nice design

**Comment by johnmusiu** [comment]
Can you reduce the size of the request ID column on view requests page? It would look better. The description column could perhaps be wider. 
Liked your status labels.
PR looks good.

**Comment by dessHub** [comment]
I love the idea of the status color variation . If you could align the button left and reduce the width on request id column it would be amazing. Otherwise great work.

**Comment by denniswanjiru** [comment]
Conventions followed at pah

**Comment by gtsofa** [comment]
I think the 
## What does this PR do?
should have said 
* Adds a user create request form
* Adds user request views
 because that's basically what i see on your first screenshot and what's on your Descriptions of Task  Completed.
That's my opinion :-) otherwise the screenshot looks great.

**Pull request merged**
